# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/user/Documents/Nexys/nexys_template/xdc/nexys_a7_100.xdc

# Block Designs: bd/top_level/top_level.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_clk_wiz_0_0/top_level_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0_0 || ORIG_REF_NAME==top_level_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_proc_sys_reset_0_0/top_level_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_proc_sys_reset_0_0 || ORIG_REF_NAME==top_level_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_uart_bridge_0_0/top_level_axi_uart_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_uart_bridge_0_0 || ORIG_REF_NAME==top_level_axi_uart_bridge_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_uartlite_0_0/top_level_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_uartlite_0_0 || ORIG_REF_NAME==top_level_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_smartconnect_0_0/top_level_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_smartconnect_0_0 || ORIG_REF_NAME==top_level_smartconnect_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_revision_0_0/top_level_axi_revision_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axi_revision_0_0 || ORIG_REF_NAME==top_level_axi_revision_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axil_slave_0_0/top_level_axil_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_level_axil_slave_0_0 || ORIG_REF_NAME==top_level_axil_slave_0_0} -quiet] -quiet

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/top_level_ooc.xdc
