# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/Documents/Nexys/nexys_template/project.srcs/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/top_level_smartconnect_0_0.xci
# IP: The module: 'top_level_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/bd_f519.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_0/bd_f519_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_2/bd_f519_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_3/bd_f519_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_4/bd_f519_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_12/bd_f519_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_13/bd_f519_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_14/bd_f519_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_15/bd_f519_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_16/bd_f519_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_17/bd_f519_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_18/bd_f519_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_19/bd_f519_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_20/bd_f519_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_21/bd_f519_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_22/bd_f519_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_23/bd_f519_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_24/bd_f519_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_25/bd_f519_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_26/bd_f519_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_27/bd_f519_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_28/bd_f519_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_29/bd_f519_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_30/bd_f519_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_31/bd_f519_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_32/bd_f519_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_33/bd_f519_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_34/bd_f519_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_35/bd_f519_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_36/bd_f519_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_37/bd_f519_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_38/bd_f519_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_39/bd_f519_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_2/bd_f519_arinsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_3/bd_f519_rinsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_4/bd_f519_awinsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_winsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_binsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_aroutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_routsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_awoutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_woutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_boutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_12/bd_f519_arni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_13/bd_f519_rni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_14/bd_f519_awni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_15/bd_f519_wni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_16/bd_f519_bni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_20/bd_f519_s00a2s_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_21/bd_f519_sarn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_22/bd_f519_srn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_23/bd_f519_sawn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_24/bd_f519_swn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_25/bd_f519_sbn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_26/bd_f519_m00s2a_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_27/bd_f519_m00arn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_28/bd_f519_m00rn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_29/bd_f519_m00awn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_30/bd_f519_m00wn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_31/bd_f519_m00bn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_33/bd_f519_m01s2a_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_34/bd_f519_m01arn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_35/bd_f519_m01rn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_36/bd_f519_m01awn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_37/bd_f519_m01wn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_38/bd_f519_m01bn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/Documents/Nexys/nexys_template/project.srcs/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/top_level_smartconnect_0_0.xci
# IP: The module: 'top_level_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/bd_f519.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_0/bd_f519_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_2/bd_f519_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_3/bd_f519_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_4/bd_f519_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_12/bd_f519_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_13/bd_f519_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_14/bd_f519_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_15/bd_f519_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_16/bd_f519_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_17/bd_f519_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_18/bd_f519_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_19/bd_f519_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_20/bd_f519_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_21/bd_f519_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_22/bd_f519_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_23/bd_f519_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_24/bd_f519_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_25/bd_f519_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_26/bd_f519_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_27/bd_f519_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_28/bd_f519_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_29/bd_f519_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_30/bd_f519_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_31/bd_f519_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_32/bd_f519_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_33/bd_f519_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_34/bd_f519_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_35/bd_f519_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_36/bd_f519_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_37/bd_f519_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_38/bd_f519_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_39/bd_f519_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_1/bd_f519_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_2/bd_f519_arinsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_3/bd_f519_rinsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_4/bd_f519_awinsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_5/bd_f519_winsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_6/bd_f519_binsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_7/bd_f519_aroutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_8/bd_f519_routsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_9/bd_f519_awoutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_10/bd_f519_woutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_11/bd_f519_boutsw_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_12/bd_f519_arni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_13/bd_f519_rni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_14/bd_f519_awni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_15/bd_f519_wni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_16/bd_f519_bni_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_20/bd_f519_s00a2s_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_21/bd_f519_sarn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_22/bd_f519_srn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_23/bd_f519_sawn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_24/bd_f519_swn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_25/bd_f519_sbn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_26/bd_f519_m00s2a_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_27/bd_f519_m00arn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_28/bd_f519_m00rn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_29/bd_f519_m00awn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_30/bd_f519_m00wn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_31/bd_f519_m00bn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_33/bd_f519_m01s2a_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_34/bd_f519_m01arn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_35/bd_f519_m01rn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_36/bd_f519_m01awn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_37/bd_f519_m01wn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/bd_0/ip/ip_38/bd_f519_m01bn_0_ooc.xdc

# XDC: /home/user/Documents/Nexys/nexys_template/project.gen/sources_1/bd/top_level/ip/top_level_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
